project:
  type: website

website:
  title: "Amy Xu"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual
